# Generated by Django 5.0.2 on 2024-08-04 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='passcode',
        ),
    ]
