# Generated by Django 5.0.2 on 2024-08-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_registration_passcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='token',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
