# Generated by Django 5.0.6 on 2024-08-08 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_registration_id_registration_rollnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='username',
        ),
    ]
