# Generated by Django 5.0.6 on 2024-08-08 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_registration_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='username',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
