# Generated by Django 5.0.6 on 2024-08-08 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_registration_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='personalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('mobileNumber', models.CharField(max_length=100)),
                ('dateOfBirth', models.DateField()),
                ('telePhone', models.CharField(max_length=100)),
                ('permanentAddress', models.TextField()),
                ('presentAddress', models.TextField()),
                ('maritalStatus', models.CharField(choices=[('Unmarried', 'Unmarried'), ('Married', 'Married')], default='Unmarried', max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=100)),
                ('username', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.registration')),
            ],
        ),
    ]
