# Generated by Django 5.0.2 on 2024-08-10 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_personalprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='type',
            field=models.CharField(default='student', max_length=100),
        ),
    ]
