# Generated by Django 5.0.2 on 2024-08-10 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_registration_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='type',
            field=models.CharField(choices=[('student', 'student'), ('admin', 'admin')], max_length=100),
        ),
    ]
