# Generated by Django 5.0.2 on 2024-08-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_registration_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='branches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branchId', models.CharField(max_length=100, unique=True)),
                ('bhanchName', models.CharField(max_length=200)),
                ('duration', models.IntegerField()),
                ('startdate', models.DateField(auto_now_add=True)),
                ('enddate', models.DateTimeField()),
            ],
        ),
    ]
