# Generated by Django 5.0.2 on 2024-08-10 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_branches_enddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branches',
            name='startdate',
            field=models.DateField(),
        ),
    ]
