# Generated by Django 5.0.2 on 2024-08-10 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_branches_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branches',
            name='enddate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
