# Generated by Django 5.0.2 on 2024-08-10 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_studentlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branches',
            name='id',
        ),
        migrations.AlterField(
            model_name='branches',
            name='branchId',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='studentlist',
            name='branchId',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.branches'),
        ),
    ]
