# Generated by Django 5.0.2 on 2024-08-10 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_branches_id_alter_branches_branchid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='branches',
            name='departmentId',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='registrationforadmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('isActive', models.IntegerField(default=0)),
                ('token', models.CharField(default=0, max_length=100)),
                ('created_data', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('student', 'student'), ('admin', 'admin')], max_length=100)),
                ('departmentId', models.CharField(max_length=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
