# Generated by Django 5.0.2 on 2024-08-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_branches_departmentid_registrationforadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='type',
            field=models.CharField(choices=[('student', 'student'), ('admin', 'admin')], default='student', max_length=100),
        ),
    ]
