# Generated by Django 5.0.2 on 2024-08-11 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_registration_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='stubjects',
            fields=[
                ('subjectCode', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('stubjectName', models.CharField(max_length=200)),
            ],
        ),
    ]
