# Generated by Django 5.0.2 on 2024-08-11 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_remove_studentlist_branchid_delete_branches_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='branches',
            fields=[
                ('departmentId', models.CharField(max_length=900)),
                ('branchId', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('bhanchName', models.CharField(max_length=200)),
                ('duration', models.IntegerField()),
                ('startdate', models.DateField()),
                ('enddate', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='studentlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('rollNumber', models.CharField(max_length=100)),
                ('branchName', models.CharField(max_length=200)),
                ('branchId', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.branches')),
            ],
        ),
    ]
