# Generated by Django 5.0.2 on 2024-08-11 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_remove_studentlist_branchid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stubjects',
            name='departmentId',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.branches'),
        ),
        migrations.AddField(
            model_name='studentlist',
            name='branchId',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.branches'),
        ),
        migrations.AlterField(
            model_name='branches',
            name='departmentId',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
