# Generated by Django 5.0.2 on 2024-08-11 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('departmentId', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='stubjects',
            name='departmentId',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.department'),
        ),
    ]
