# Generated by Django 5.0.2 on 2024-08-11 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_department_alter_stubjects_departmentid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stubjects',
            name='departmentId',
        ),
    ]
