# Generated by Django 5.0.2 on 2024-08-11 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_remove_stubjects_departmentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='stubjects',
            name='departmentId',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.department'),
        ),
        migrations.AlterField(
            model_name='branches',
            name='departmentId',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.department'),
        ),
    ]
