# Generated by Django 5.0.2 on 2024-08-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_alter_branches_departmentid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentmarkes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollNumber', models.CharField(max_length=100)),
                ('SubjectCode', models.CharField(max_length=100)),
                ('subjectName', models.CharField(max_length=100)),
                ('marks', models.IntegerField(default=0)),
            ],
        ),
    ]
