# Generated by Django 5.0.2 on 2024-08-13 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_attendance_branchid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='branchId',
        ),
    ]
