# Generated by Django 5.0.2 on 2024-08-13 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_remove_attendance_branchid'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='branchId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.branches'),
        ),
    ]
