# Generated by Django 5.0.2 on 2024-08-14 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_alter_attendance_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='branchId',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='subject',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='present',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.registration'),
            preserve_default=False,
        ),
    ]
