# Generated by Django 5.1 on 2024-08-17 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_remove_attendance_branchid_remove_attendance_subject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='student',
        ),
    ]
