# Generated by Django 5.1 on 2024-08-18 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_attendance_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='type',
            field=models.CharField(choices=[('student', 'student'), ('admin', 'admin'), ('faculty', 'faculty')], default='student', max_length=100),
        ),
        migrations.AlterField(
            model_name='registrationforadmin',
            name='type',
            field=models.CharField(choices=[('student', 'student'), ('admin', 'admin'), ('faculty', 'faculty')], max_length=100),
        ),
        migrations.CreateModel(
            name='facultyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('mobileNumber', models.CharField(max_length=100)),
                ('dateOfBirth', models.DateField()),
                ('telePhone', models.CharField(max_length=100)),
                ('permanentAddress', models.TextField()),
                ('presentAddress', models.TextField()),
                ('maritalStatus', models.CharField(choices=[('Unmarried', 'Unmarried'), ('Married', 'Married')], default='Unmarried', max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=100)),
                ('username', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.registrationforadmin')),
            ],
        ),
    ]
