# Generated by Django 5.1 on 2024-08-18 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_alter_registration_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
