# Generated by Django 5.1 on 2024-08-18 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='student',
        ),
        migrations.RemoveField(
            model_name='branches',
            name='departmentId',
        ),
        migrations.RemoveField(
            model_name='studentlist',
            name='branchId',
        ),
        migrations.RemoveField(
            model_name='stubjects',
            name='departmentId',
        ),
        migrations.RemoveField(
            model_name='facultydetails',
            name='username',
        ),
        migrations.RemoveField(
            model_name='personalprofile',
            name='username',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='user',
        ),
        migrations.RemoveField(
            model_name='registrationforadmin',
            name='user',
        ),
        migrations.DeleteModel(
            name='studentmarkes',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='branches',
        ),
        migrations.DeleteModel(
            name='studentlist',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='stubjects',
        ),
        migrations.DeleteModel(
            name='facultyDetails',
        ),
        migrations.DeleteModel(
            name='personalProfile',
        ),
        migrations.DeleteModel(
            name='registration',
        ),
        migrations.DeleteModel(
            name='registrationforadmin',
        ),
    ]
