# Generated by Django 5.1 on 2024-08-18 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0046_remove_attendance_student_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('departmentId', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='studentmarkes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollNumber', models.CharField(max_length=100)),
                ('SubjectCode', models.CharField(max_length=100)),
                ('subjectName', models.CharField(max_length=100)),
                ('marks', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='branches',
            fields=[
                ('branchId', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('bhanchName', models.CharField(max_length=200)),
                ('duration', models.IntegerField()),
                ('startdate', models.DateField()),
                ('enddate', models.DateField(blank=True, null=True)),
                ('departmentId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.department')),
            ],
        ),
        migrations.CreateModel(
            name='registration',
            fields=[
                ('rollNumber', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('isActive', models.IntegerField(default=0)),
                ('token', models.CharField(default=0, max_length=100)),
                ('created_data', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('student', 'student'), ('admin', 'admin'), ('faculty', 'faculty')], default='student', max_length=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='personalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('mobileNumber', models.CharField(max_length=100)),
                ('dateOfBirth', models.DateField()),
                ('telePhone', models.CharField(max_length=100)),
                ('permanentAddress', models.TextField()),
                ('presentAddress', models.TextField()),
                ('maritalStatus', models.CharField(choices=[('Unmarried', 'Unmarried'), ('Married', 'Married')], default='Unmarried', max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=100)),
                ('username', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.registration')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('present', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.registration')),
            ],
        ),
        migrations.CreateModel(
            name='registrationforadmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('isActive', models.IntegerField(default=0)),
                ('token', models.CharField(default=0, max_length=100)),
                ('created_data', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('student', 'student'), ('admin', 'admin'), ('faculty', 'faculty')], max_length=100)),
                ('departmentId', models.CharField(max_length=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='facultyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('mobileNumber', models.CharField(max_length=100)),
                ('dateOfBirth', models.DateField()),
                ('telePhone', models.CharField(max_length=100)),
                ('permanentAddress', models.TextField()),
                ('presentAddress', models.TextField()),
                ('maritalStatus', models.CharField(choices=[('Unmarried', 'Unmarried'), ('Married', 'Married')], default='Unmarried', max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=100)),
                ('username', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.registrationforadmin')),
            ],
        ),
        migrations.CreateModel(
            name='stubjects',
            fields=[
                ('subjectCode', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('stubjectName', models.CharField(max_length=200)),
                ('departmentId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.department')),
            ],
        ),
        migrations.CreateModel(
            name='studentlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('rollNumber', models.CharField(max_length=100)),
                ('branchName', models.CharField(max_length=200)),
                ('branchId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.branches')),
            ],
        ),
    ]
