# Generated by Django 5.1 on 2024-08-18 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='type',
            field=models.CharField(choices=[('student', 'student'), ('admin', 'admin')], default='student', max_length=100),
        ),
        migrations.AlterField(
            model_name='registrationforadmin',
            name='type',
            field=models.CharField(choices=[('student', 'student'), ('admin', 'admin')], max_length=100),
        ),
    ]
