# Generated by Django 5.1 on 2024-08-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_alter_registration_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='message_send',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=200)),
                ('receiver', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
        ),
    ]
