# Generated by Django 5.1 on 2024-08-27 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_message_send'),
    ]

    operations = [
        migrations.CreateModel(
            name='sendpdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('pdf_data', models.FileField(default=None, null=True, upload_to='pdfs/')),
                ('sender', models.TextField()),
                ('receiver_branch_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.branches')),
            ],
        ),
    ]
