# Generated by Django 5.1 on 2024-08-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_sendpdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='messageviewstatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=200)),
                ('view_status', models.IntegerField(default=0)),
                ('message_id', models.CharField(max_length=200)),
                ('receiver', models.CharField(max_length=200)),
            ],
        ),
    ]
