# Generated by Django 5.1 on 2024-08-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_messageviewstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='newbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_code', models.TextField(max_length=200)),
                ('book_subject', models.TextField(max_length=200)),
                ('book_name', models.TextField(max_length=200)),
                ('auther_name', models.TextField(max_length=200)),
                ('book_pdf', models.FileField(default=True, null=True, upload_to='books/')),
            ],
        ),
    ]
