# Generated by Django 5.1 on 2024-09-09 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0052_newbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookrequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollnumber', models.CharField(max_length=300)),
                ('branch_id', models.CharField(max_length=300)),
                ('branch_name', models.CharField(max_length=300)),
                ('book_name', models.CharField(max_length=200)),
                ('auther_name', models.CharField(max_length=300)),
                ('Date_for_request', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
