# Generated by Django 5.1 on 2024-09-09 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0053_bookrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalprofile',
            name='username',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='student',
        ),
        migrations.DeleteModel(
            name='registration',
        ),
    ]
