# Generated by Django 5.1 on 2024-09-09 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0054_remove_personalprofile_username_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('rollNumber', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('isActive', models.IntegerField(default=0)),
                ('token', models.CharField(default=0, max_length=100)),
                ('created_data', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('student', 'student'), ('admin', 'admin')], default='student', max_length=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.registration'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalprofile',
            name='username',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.registration'),
        ),
    ]
