# Generated by Django 5.1 on 2024-09-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0055_registration_attendance_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrequest',
            name='status',
            field=models.CharField(default='Pending', max_length=200, null=True),
        ),
    ]
