# Generated by Django 5.1 on 2024-09-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0056_bookrequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='busdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bus_number', models.IntegerField()),
                ('college_shift', models.IntegerField()),
                ('Boarding_point', models.TextField()),
                ('Dropping_point', models.TextField()),
            ],
        ),
    ]
