# Generated by Django 5.1 on 2024-09-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0057_busdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='busdetails',
            name='rollnumber',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
